// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  // Retrieve Firebase configuration details from environment variables

  static final androidApiKey = dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '';
  static final androidAppId = dotenv.env['FIREBASE_ANDROID_APP_ID'] ?? '';

  static FirebaseOptions android = FirebaseOptions(
    apiKey: androidApiKey,
    appId: androidAppId,
    messagingSenderId: '5027387074',
    projectId: 'chat-app-d2aff',
    storageBucket: 'chat-app-d2aff.appspot.com',
  );

  static final iosApiKey = dotenv.env['FIREBASE_IOS_API_KEY'] ?? '';
  static final iosAppId = dotenv.env['FIREBASE_IOS_APP_ID'] ?? '';

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: iosApiKey,
    appId: iosAppId,
    messagingSenderId: '5027387074',
    projectId: 'chat-app-d2aff',
    storageBucket: 'chat-app-d2aff.appspot.com',
    androidClientId:
        '5027387074-204474lll3qeda6o0etmmg885lrcl4ur.apps.googleusercontent.com',
    iosClientId:
        '5027387074-ohm064j2s596jfenpn92eqdpb92tf12v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
